import type {
  CompetencyStatus,
  DomainCode,
  GapPriority,
  Level,
} from "@/demo/types";

export type CompetencyRecord = {
  id: string;
  name: string;
  domain: DomainCode;
  domainLabel: string;
  currentLevel: Level;
  targetLevel: Level;
  status: CompetencyStatus;
  priority: GapPriority;
  lastAssessed: string;
  evidence: string;
  recommendedAction: string;
  gapReason: string;
};

export const domainReadiness: { code: DomainCode; label: string; percent: number }[] = [
  { code: "STAT", label: "Statistical", percent: 61 },
  { code: "TECH", label: "Technical", percent: 78 },
  { code: "GOV", label: "Digital governance", percent: 84 },
  { code: "BEH", label: "Behavioural", percent: 69 },
];

export const competencies: CompetencyRecord[] = [
  {
    id: "stat-data-analysis",
    name: "Statistical Data Analysis",
    domain: "STAT",
    domainLabel: "Statistical",
    currentLevel: "L2",
    targetLevel: "L4",
    status: "Priority Gap",
    priority: "High",
    lastAssessed: "12 Mar 2026",
    evidence: "Diagnostic items on interpretation of tabulated results were missed at L3 and L4.",
    recommendedAction: "Complete the iGOT programme on analysis of official datasets, then sit the follow-up assessment.",
    gapReason:
      "Required level for a Statistical Officer is L4. Demonstrated level on the prepared profile is L2. The gap is two levels because L3 items on interpreting official tables were not met.",
  },
  {
    id: "stat-survey-methodology",
    name: "Survey Methodology",
    domain: "STAT",
    domainLabel: "Statistical",
    currentLevel: "L2",
    targetLevel: "L3",
    status: "Priority Gap",
    priority: "Medium",
    lastAssessed: "12 Mar 2026",
    evidence: "Sampling-frame and coverage items at L3 were not met.",
    recommendedAction: "Take the NSSTA survey methodology practicum before the next field exercise.",
    gapReason:
      "Required level is L3. Demonstrated level is L2. One L3 item on coverage rules for household surveys was missed, so the level is not yet met.",
  },
  {
    id: "stat-data-quality",
    name: "Data Quality",
    domain: "STAT",
    domainLabel: "Statistical",
    currentLevel: "L3",
    targetLevel: "L4",
    status: "Priority Gap",
    priority: "Medium",
    lastAssessed: "12 Mar 2026",
    evidence: "Validation-rule items at L4 remain open. L3 checks were met.",
    recommendedAction: "Use the TPAC data-quality workshop, then retake the L4 diagnostic items.",
    gapReason:
      "Required level is L4. Demonstrated level is L3. The single-level gap is the unmet L4 item on applying a data-quality framework to a published table.",
  },
  {
    id: "stat-sampling",
    name: "Sampling Design",
    domain: "STAT",
    domainLabel: "Statistical",
    currentLevel: "L3",
    targetLevel: "L4",
    status: "Moderate Gap",
    priority: "Medium",
    lastAssessed: "4 Feb 2026",
    evidence: "L1–L3 sampling items met. L4 allocation item remains open.",
    recommendedAction: "Review the sampling note used by the training admin, then attempt the published L4 item when it is released.",
    gapReason: "Required L4 is one level above the demonstrated L3. The unmet item concerns sample allocation across strata.",
  },
  {
    id: "stat-national-accounts",
    name: "National Accounts",
    domain: "STAT",
    domainLabel: "Statistical",
    currentLevel: "L3",
    targetLevel: "L3",
    status: "Meets Target",
    priority: "Low",
    lastAssessed: "18 Jan 2026",
    evidence: "L3 items on production and expenditure accounts were met.",
    recommendedAction: "No immediate programme. Retain the current level for the next annual review.",
    gapReason: "Demonstrated level matches the required level.",
  },
  {
    id: "stat-price",
    name: "Price Statistics",
    domain: "STAT",
    domainLabel: "Statistical",
    currentLevel: "L4",
    targetLevel: "L4",
    status: "Meets Target",
    priority: "Low",
    lastAssessed: "18 Jan 2026",
    evidence: "Index construction and rebasing items at L4 were met.",
    recommendedAction: "No immediate programme.",
    gapReason: "Demonstrated level matches the required level.",
  },
  {
    id: "stat-sdg",
    name: "SDG Indicators",
    domain: "STAT",
    domainLabel: "Statistical",
    currentLevel: "L2",
    targetLevel: "L3",
    status: "Developing",
    priority: "Medium",
    lastAssessed: "2 Dec 2025",
    evidence: "Indicator metadata at L2 is in place. Disaggregation practice at L3 is in progress.",
    recommendedAction: "Continue the blended SDG indicator workshop already on the pathway.",
    gapReason: "Required L3 is not yet demonstrated. L2 is met and L3 practice is underway.",
  },
  {
    id: "stat-labour",
    name: "Labour Statistics",
    domain: "STAT",
    domainLabel: "Statistical",
    currentLevel: "L3",
    targetLevel: "L3",
    status: "Meets Target",
    priority: "Low",
    lastAssessed: "2 Dec 2025",
    evidence: "Employment and unemployment classification items at L3 were met.",
    recommendedAction: "No immediate programme.",
    gapReason: "Demonstrated level matches the required level.",
  },
  {
    id: "tech-statistical-computing",
    name: "Statistical Computing Practice",
    domain: "TECH",
    domainLabel: "Technical",
    currentLevel: "L3",
    targetLevel: "L4",
    status: "Moderate Gap",
    priority: "Medium",
    lastAssessed: "20 Feb 2026",
    evidence: "Approved statistical software is used for routine tables. L4 reproducible-release practice is open.",
    recommendedAction: "Complete the NSSTA module on reproducible official tables.",
    gapReason: "Required L4 is one level above demonstrated L3. The open practice is documenting a reproducible table release, not a programming exercise.",
  },
  {
    id: "tech-visualisation",
    name: "Data Visualisation for Releases",
    domain: "TECH",
    domainLabel: "Technical",
    currentLevel: "L4",
    targetLevel: "L4",
    status: "Meets Target",
    priority: "Low",
    lastAssessed: "20 Feb 2026",
    evidence: "Chart choice and disclosure-safe graphics at L4 were met.",
    recommendedAction: "No immediate programme.",
    gapReason: "Demonstrated level matches the required level.",
  },
  {
    id: "tech-open-data",
    name: "Open Data Practice",
    domain: "TECH",
    domainLabel: "Technical",
    currentLevel: "L4",
    targetLevel: "L4",
    status: "Meets Target",
    priority: "Low",
    lastAssessed: "11 Nov 2025",
    evidence: "Machine-readable release and licence items at L4 were met.",
    recommendedAction: "No immediate programme.",
    gapReason: "Demonstrated level matches the required level.",
  },
  {
    id: "tech-gis",
    name: "Geospatial Statistics",
    domain: "TECH",
    domainLabel: "Technical",
    currentLevel: "L2",
    targetLevel: "L3",
    status: "Developing",
    priority: "Low",
    lastAssessed: "11 Nov 2025",
    evidence: "Map reading at L2 is met. Small-area estimation awareness at L3 is in progress.",
    recommendedAction: "Schedule the TPAC geospatial briefing after the priority statistical gaps.",
    gapReason: "Required L3 is not yet demonstrated. This is a developing competency, not a priority gap.",
  },
  {
    id: "gov-privacy",
    name: "Data Privacy",
    domain: "GOV",
    domainLabel: "Digital governance",
    currentLevel: "L4",
    targetLevel: "L4",
    status: "Meets Target",
    priority: "Low",
    lastAssessed: "8 Jan 2026",
    evidence: "Personal-data handling and purpose limitation at L4 were met.",
    recommendedAction: "No immediate programme.",
    gapReason: "Demonstrated level matches the required level.",
  },
  {
    id: "gov-security",
    name: "Information Security Practice",
    domain: "GOV",
    domainLabel: "Digital governance",
    currentLevel: "L4",
    targetLevel: "L4",
    status: "Meets Target",
    priority: "Low",
    lastAssessed: "8 Jan 2026",
    evidence: "Access control and incident reporting at L4 were met.",
    recommendedAction: "No immediate programme.",
    gapReason: "Demonstrated level matches the required level.",
  },
  {
    id: "gov-dpi",
    name: "Digital Public Infrastructure",
    domain: "GOV",
    domainLabel: "Digital governance",
    currentLevel: "L4",
    targetLevel: "L4",
    status: "Meets Target",
    priority: "Low",
    lastAssessed: "8 Jan 2026",
    evidence: "Use of approved digital channels for statistical releases at L4 was met.",
    recommendedAction: "No immediate programme.",
    gapReason: "Demonstrated level matches the required level.",
  },
  {
    id: "beh-communication",
    name: "Official Communication",
    domain: "BEH",
    domainLabel: "Behavioural",
    currentLevel: "L3",
    targetLevel: "L4",
    status: "Moderate Gap",
    priority: "Medium",
    lastAssessed: "15 Jan 2026",
    evidence: "Briefing notes at L3 are sound. L4 handling of revision notices is open.",
    recommendedAction: "Attend the iGOT briefing on communicating statistical revisions.",
    gapReason: "Required L4 is one level above demonstrated L3.",
  },
  {
    id: "beh-ethics",
    name: "Ethical Practice",
    domain: "BEH",
    domainLabel: "Behavioural",
    currentLevel: "L4",
    targetLevel: "L4",
    status: "Meets Target",
    priority: "Low",
    lastAssessed: "15 Jan 2026",
    evidence: "Independence and confidentiality items at L4 were met.",
    recommendedAction: "No immediate programme.",
    gapReason: "Demonstrated level matches the required level.",
  },
  {
    id: "beh-coordination",
    name: "Stakeholder Coordination",
    domain: "BEH",
    domainLabel: "Behavioural",
    currentLevel: "L3",
    targetLevel: "L4",
    status: "Developing",
    priority: "Low",
    lastAssessed: "15 Jan 2026",
    evidence: "Cross-division coordination at L3 is established. L4 planning with training counterparts is in progress.",
    recommendedAction: "Pair the communication programme with one coordination exercise.",
    gapReason: "Required L4 is not yet demonstrated. Progress at L3 is recorded.",
  },
];

export const priorityGaps = competencies.filter((item) => item.status === "Priority Gap");

export const developingCompetencies = competencies.filter(
  (item) => item.status === "Developing" || item.status === "Moderate Gap"
);

export const meetingTarget = competencies.filter((item) => item.status === "Meets Target");
